export { Paso01Contexto } from './Paso01Contexto'
export { Paso02Problema } from './Paso02Problema'
export { Paso03Hipotesis } from './Paso03Hipotesis'
export { Paso05Diagnostico } from './Paso05Diagnostico'
export { Paso07Costo } from './Paso07Costo'
export { Paso08CausaRaiz } from './Paso08CausaRaiz'
export { Paso09Plan } from './Paso09Plan'
export { Paso10Accountability } from './Paso10Accountability'
